name: Visual Tests

on:
  deployment_status:

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}

jobs:
  run-visual:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: debug
        run: echo Testing URL ${{ github.event.deployment_status.environment_url }}
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.environment_url }}

  batch-completion-notification:
    needs: run-visual
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Update Applitools batch status
        uses: wei/curl@v1.1.1
        with:
          args: -d "" -X POST https://eyesapi.applitools.com/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}
